name: 365activesports
favicon: null
layout_spectrum: 0.20462169381789863
typography_spectrum: 0.17945232545025647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.025559384608641267
  lightness: 0.07998925913125277
  saturation: 0.6017726566642523
  rhythmicContrast: 0.9985770594794303
purpose: []
