name: 365activesports
favicon: null
layout_spectrum: 0.23713
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00aeef'
    - '#61ccf4'
    - '#a2e1f8'
    - '#29bbf1'
  brandStrength: 1
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 1
purpose: []
